name: CI Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  CI-pull-request:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependências
      run: npm install --no-save

    - name: Rebuild
      run: npm run rebuild